#!/usr/bin/perl

# Last Edit: 2006 Apr 19, 07:41:02 PM

use strict;
use warnings;

use Text::Template;
use YAML qw/ LoadFile /;
use Games::Tournament::RoundRobin;
use Games::League::Member;

my $leagueRound = $ARGV[0];
(my $shortForm = $leagueRound) =~ s/^.*([a-z]\d+)$/$1/;
# my $league = substr( $shortForm, 0, 1);
# (my $league = $leagueRound) =~ s/^(.*[a-z])\d+$/$1/;
my $round = LoadFile("$shortForm.yaml");
# my $register = LoadFile("$ENV{HOME}/$league/register.yaml");
my $league = LoadFile( "../class.yaml" );
my @members = @{$league->{member}};
my %ids = map { $_->{name} => $_->{id} } @members;
my %names = map { $_->{id} => $_->{name} } @members;

use IO::All;

my $io = io 'form.tmpl';
my $tmplString = $io->all;

my $groups = $round->{group};
my $id = $round->{id};
my @latex = (
		{ page => 1, xy => "0,0" },
		{ page => 1, xy => "8,0" },
		{ page => 1, xy => "0,8" },
		{ page => 1, xy => "8,8" },
		{ page => 2, xy => "0,0" },
		{ page => 2, xy => "8,0" },
		{ page => 2, xy => "0,8" },
		{ page => 2, xy => "8,8" },
		{ page => 3, xy => "0,0" },
		{ page => 3, xy => "8,0" },
		{ page => 3, xy => "0,8" },
		{ page => 3, xy => "8,8" },
	);
my $paging = 0;
my $threepages = 0;

foreach my $group ( keys %$groups )
{
	my @group =  @{$round->{group}->{$group}}; 
	my $k;
	my (@lineup, $roundrobin, @players, $partners);
	@lineup = map {
		my $playerId = $ids{$_};
		my $member = Games::League::Member->new( 
			index => $k++, name => $_, id => $playerId);
	} @group;
	$roundrobin =
	Games::Tournament::RoundRobin->new(v => 3, league => \@lineup)
					unless $group eq 'Bye';
	@players = map { $roundrobin->partner('Bye', $_) } 1..3 if $roundrobin;
	@players = @group if $group eq 'Bye';
	foreach my $player ( @players )
	{
		$partners = $roundrobin->realPartners($player) if $roundrobin;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$group}
{$player}
{$ids{$player}}
";
		 if ($roundrobin)
		{
			$tmplString .= "{$partners->[0]}
{$partners->[0]->{id}}
{$partners->[1]}
{$partners->[1]->{id}}
{$lineup[0] \\hfill $lineup[1] \\hfill $lineup[2]}
";
		}						
		else {
			$tmplString .= "{}{}{}{}{}";
		}
		$tmplString .= "\\end{textblock}\n";

		if ($paging == 3 or $paging == 7 or $paging == 11 )
		{
			$tmplString .= 
"\\begin{tiny}" . ($threepages + $latex[$paging]->{page}) . "\\end{tiny}\\newpage\n\n";
		}
		if ($paging == 11) { $threepages = $threepages+3; $paging = 0; }
		else { $paging++; }
	}

}

$tmplString .= '
\end{document}
';

# my $league = substr( $leagueShortForm, 0, 1);
my $template = Text::Template->new(TYPE => 'STRING'
				, SOURCE => $tmplString
				, DELIMITERS => [ '<tmpl>', '</tmpl>' ] );

$round->{autogen} = "% This file, form.tex was autogenerated on " . localtime() . "by form.pl";

my $tmplHash = $round;
$tmplHash->{league} = $league->{league};
@{$tmplHash->{assistantId}} = map { $ids{$_} } @{$round->{assistant}};

open TEX, ">form.tex";
print TEX $template->fill_in( HASH => $tmplHash );

