#!/usr/bin/perl

use strict;
use warnings;

use Text::Template;
use YAML qw/ LoadFile /;

my $round = LoadFile( "round.yaml" );
my $league = LoadFile( "../league.yaml" );
my @members = @{$league->{member}};
my %ids = map { $_->{name} => $_->{id} } @members;
my %names = map { $_->{id} => $_->{name} } @members;

my $passLetters = $round->{pass};
my $passGrade = 9;
my $letterGrade = sub {
	my $grade = shift;
	return 1 + int (($passLetters/$passGrade**2.3)*$grade**2.3);
};
my @grades = ( 9, 11, 13, 15 );
my @letters = map { $letterGrade->($_) } @grades;
my $groupLetters = $letters[-1];
my $indLetters = int ($groupLetters/2);

use IO::All;

my $io = io 'form.tmpl';
my $tmplString = $io->all;

my $n = 1;
my $groups = $round->{group};
PAGELOOP: while ( my $group = each %$groups )
{
	$tmplString .= "
\\begin{textblock}{8}(0,0)
\\textblocklabel{picture1}
\\mycard{\$\\heartsuit\$}
{$group}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,0)
\\textblocklabel{picture4}
\\mycard{\$\\spadesuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}
";
	$group = each %$groups;
	$tmplString .= "
\\begin{textblock}{8}(0,8)
\\textblocklabel{picture3}
\\mycard{\$\\diamondsuit\$}
{$group}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,8)
\\textblocklabel{picture2}
\\mycard{\$\\clubsuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}

\\begin{tiny}$n\\end{tiny}\\\\
\\newpage

";
	$n++;
	last PAGELOOP unless defined $group;
}

$tmplString .= '
\end{document}
';

my $template = Text::Template->new(TYPE => 'STRING'
				, SOURCE => $tmplString
				, DELIMITERS => [ '<tmpl>', '</tmpl>' ] );

my $form;
$form->{autogen} = "% This file, form.tex was autogenerated on " . localtime() . "by form.pl";
$form->{league} = $league->{league};
# $form->{assistant} = $round->{assistant};
$form->{round} = $round->{round};
$form->{week} = $round->{week};
$form->{indLetters} = $indLetters;
$form->{groupLetters} = $groupLetters;
$form->{letters} = \@letters;
$form->{grades} = \@grades;

open TEX, ">form.tex";
print TEX $template->fill_in( HASH => $form );

