#!/usr/bin/perl

# Last Edit: 2016 Jun 23, 08:48:08 AM
# $Id: /cloze/branches/ctest/dic.pl 1134 2007-03-17T11:05:37.500624Z greg  $

use strict;
use warnings;

use FindBin '$Bin';
use lib "$Bin";

use Getopt::Long;
use Pod::Usage;

my $man = 0;
my $help = 0;
my $s = '';
my $f = 0;

GetOptions (
	'help|?' => \$help, man => \$man,
	's=s' => \$s, 'f=i' => \$f)
		or pod2usage(2);
pod2usage(1) if $help;
pod2usage(-exitstatus => 0, -verbose => 2) if $man;

use IO::All;
use YAML qw/LoadFile/;
use Parse::RecDescent;
use Text::Template;
use Cloze qw/cloze/;
use List::Util qw/shuffle/;

our $RD_HINT = 1;

# my $round = LoadFile( "round.yaml" );
# my $league = LoadFile( "../league.yaml" );
# my @members = @{$league->{member}};
# my %ids = map { $_->{name} => $_->{id} } @members;
# my %names = map { $_->{id} => $_->{name} } @members;

my $textSources = shift @ARGV;
my ($text, $question) = LoadFile "$textSources/dic.yaml";

my $fields = shift( @$text );


my @latex = (
		{ page => 1, xy => "0,0" },
		{ page => 1, xy => "0,4" },
		{ page => 1, xy => "8,0" },
		{ page => 1, xy => "8,4" },
		{ page => 1, xy => "0,8" },
		{ page => 1, xy => "0,12" },
		{ page => 1, xy => "8,8" },
		{ page => 1, xy => "8,12" },
		{ page => 2, xy => "0,0" },
		{ page => 2, xy => "0,4" },
		{ page => 2, xy => "8,0" },
		{ page => 2, xy => "8,4" },
		{ page => 2, xy => "0,8" },
		{ page => 2, xy => "0,12" },
		{ page => 2, xy => "8,8" },
		{ page => 2, xy => "8,12" },
		# { page => 2, xy => "8,0" },
		# { page => 2, xy => "0,0" },
		# { page => 2, xy => "8,8" },
		# { page => 2, xy => "0,8" },
		# { page => 3, xy => "8,0" },
		# { page => 3, xy => "0,0" },
		# { page => 3, xy => "8,8" },
		# { page => 3, xy => "0,8" },
	);
my $paging = 0;
my $threepages = 0;

my $tmpl = io "$Bin/dic.tmpl";
my $tmplString = $tmpl->all;

my @ids = @ARGV;
my %texts;
my %next;
my $identifier;
my %romanize = (
	0 => "Zero", 1 => "One", 2 => "Two", 3 =>"Three"
	, 4 => "Four", 5 => "Five", 6 => "Six", 7 =>"Seven"
	, 8 => "Eight", 9 => "Nine", 10 => "Ten", 11 =>"Eleven" 
);

for my $id ( @ids ) {
	$identifier = "$s-$f";
	for my $text ( grep { $_->[0] eq $identifier } @$text ) {
		my $i = 0;
		my $lines = $text->[4];
		my @lines = split /\n/, $lines;
		my $unclozeables = $text->[5];
		my $text = cloze($unclozeables, @lines);
		my $textA = $text->{A};
		my $textB = $text->{B};
		my @text;
		@text[0,1] = ($textA, $textB);

		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[0]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[1]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[1]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[1]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[0]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[1]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[1]}
\\end{textblock}\n";
		&paging;
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard
{$text[1]}
\\end{textblock}\n";
		&paging;
	}
}

$tmplString .= '
\end{document}
';

my $quiz;
# $quiz->{cardIdentifier} = join ' ', map { m{^/.*/.*/(.*)$};$1 } @$textSources;
$quiz->{cardIdentifier} = "$identifier";
$quiz->{story} = $s;
$quiz->{form} = $romanize{ $f };
$quiz->{autogen} = "% This file, cards.tex was autogenerated on " . localtime() . "by dic.pl out of cards.tmpl";

my $template = Text::Template->new(TYPE => 'STRING', SOURCE => $tmplString
				, DELIMITERS => [ '<TMPL>', '</TMPL>' ] );
open TEX, ">$textSources/dic_${s}_$f.tex";
print TEX $template->fill_in( HASH => $quiz );

sub nextText
{
	my $texts = shift;
	my $number = @$texts;
	my $index = 0;
	my ($nextText, $nextFile);
	return sub
	{
		$nextText = $texts->[$index];
                if (++$index == $number)
                {
                        $index = 0;
                        $texts->[0..$number-1] = $texts->[shuffle(0..$number-1)];
                }
		# $index = int rand( $number );
		return ( $nextText->{A}, $nextText->{B} );
	};
}

sub paging
{	if ($paging == 7 or $paging == 15 or $paging == 23 )
	{
		$tmplString .= "
\\begin{tiny}" . ($threepages + $latex[$paging]->{page}) . "\\end{tiny}\\newpage\n\n";
	}
	if ($paging == 23) { $threepages = $threepages+3; $paging = 0; }
	else { $paging++; }
}
