---
id: A706
pairs:
  1 : [02, 01]
  2 : [04, 03]
  3 : [06, 05]
  4 : [08, 07]
  5 : [10, 09]
  6 : [12, 11]
  7 : [14, 13]
  8 : [16, 15]
  9 : [18, 17]
  10: [20, 19]
  11: [22, 21]
  12: [24, 23]
  13: [26, 25]
  14: [28, 27]
  15: [30, 29]
  16: [32, 31]
  17: [34, 33]
  18: [36, 35]
  19: [38, 37]
  20: [40, 39]
  21: [42, 41]
  22: [44, 43]
  23: [46, 45]
  24: [48, 47]
  25: [50, 49]
pairexperts:
  1 : [11, 01]
  2 : [04, 10]
  3 : [15, 05]
  4 : [08, 14]
  5 : [03, 09]
  6 : [12, 02]
  7 : [07, 13]
  8 : [16, 06]
  9 : [27, 17]
  10: [20, 26]
  11: [31, 21]
  12: [24, 30]
  13: [19, 25]
  14: [28, 18]
  15: [23, 29]
  16: [32, 22]
  17: [43, 33]
  18: [36, 42]
  19: [47, 37]
  20: [40, 46]
  21: [35, 41]
  22: [44, 34]
  23: [39, 45]
  24: [48, 38]
  25: [56, 49]
colors:
  1 : #ff0000
  2 : #ff5050
  3 : #ff6600
  4 : #ff9933

  5 : #ffcc00
  6 : #ffff66
  7 : #ccff66
  8 : #99ff66

  9 : #66ff33
  10: #66ff99
  11: #66ffcc
  12: #00ffcc

  13: #00ffff
  14: #33cccc
  15: #00ccff
  16: #0099ff

  17: #66a3e0
  18: #6685e0
  19: #6666ff
  20: #9999eb

  21: #9999cc
  22: #666669
  23: #757575
  24: #909090

  25: #c5c5c5
  26: #f0f0f0

  1-1 : Black
  1-2 : Blue
  1-3 : Brown
  1-4 : Green
  1-5 : Gray
  2-1 : Black
  2-2 : Blue
  2-3 : Green
  2-4 : Orange
  3-1 : Pink
  3-2 : Purple
  3-3 : Red
  3-4 : White
  4-1 : Yellow
  4-2 : Orange
  4-3 : Pink
  4-4 : Purple
  5-1 : Green
  5-2 : Green
  6-1 : Green
  6-2 : Green
  7-1 : Blue
  7-2 : Blue

  8-1 : Orange
  8-2 : Orange
  9-1 : Pink
  9-2 : Pink
  10-1 : Purple
  10-2 : Purple
  11-1 : Red
  11-2 : Red
  12-1 : White
  12-2 : White
  13-1 : Orange
  13-2 : Orange
  14-1 : Yellow
  14-2 : Yellow

  Black     : Gray
  BlackBlack: Gray
  Blue      : Blue
  BlueBlue  : Blue
  Brown     :
  BrownBrown:
  DarkGreen :
  Gray      :
  GrayGray  : Gray
  Green     :
  LightBlue :
  LightGreen:
  Orange    :
  Pink      :
  Purple    :
  Red       :
  White     :
  WhiteWhite: White
  Yellow    :
  YellowYellow: Yellow
fours:
  Green     : [25, 25a, 26, 26a]
  Gray      : [23, 15, 24, 16]
  Brown     : [21, 13, 22, 14]
  Blue      : [19, 11, 20, 12]
  Black     : [17, 09, 18, 10]
  BlackBlack: [01, 02, 03, 04]
  BlueBlue  : [05, 06, 07, 08]

  Orange    : [37, 27, 38, 28]
  Pink      : [39, 29, 40, 30]
  Purple    : [41, 31, 42, 32]
  Red       : [43, 33, 44, 34]
  White     : [45, 35, 46, 36]
  WhiteWhite: [47, 48, 49, 50]
  Yellow    : [51, 52, 53, 54]
  YellowYellow: [55, 56, 56a, 46a]

  BrownBrown: [ Xa, Xb, Xc, Xd ]
  GrayGray  : [ Ya, Yb, Yc, Yd ]
threes:
  2-3         : [01, 02, 03]
  2-2         : [05, 06, 07]

  2-1         : [16, 25, 25a]
  1-5         : [23, 15, 24]
  1-4         : [13, 22, 14]
  1-3         : [20, 12, 21]
  1-2         : [10, 19, 11]
  1-1         : [17, 09, 18]

  GreenGreen  : [01, 02, 03]
  BlueBlue    : [05, 06, 07]

  BlackBlack  : [16, 25, 25a]
  Green       : [23, 15, 24]
  Gray        : [13, 22, 14]
  Brown       : [20, 12, 21]
  Blue        : [10, 19, 11]
  Black       : [17, 09, 18]

  YellowYellow: [47, 48, 49]
  PurplePurple: [50, 51, 52]
  PinkPink    : [53, 54, 55]

  4-2         : [46, 36, 56]
  2-4         : [37, 27, 38]
  3-1         : [28, 39, 29]
  3-2         : [40, 30, 41]
  3-3         : [31, 42, 32]
  3-4         : [43, 33, 44]
  4-1         : [34, 45, 35]

  YellowYellow: [47, 48, 49]
  4-4         : [50, 51, 52]
  4-3         : [53, 54, 55]

  OrangeOrange: [46, 36, 56]
  Orange      : [37, 27, 38]
  Pink        : [28, 39, 29]
  Purple      : [40, 30, 41]
  Red         : [31, 42, 32]
  White       : [43, 33, 44]
  Yellow      : [34, 45, 35]
twos:
  1-1     : [17, 09]
  1-2     : [18, 10]
  2-1     : [19, 11]
  2-2     : [20, 12]
  3-1     : [21, 13]
  3-2     : [22, 14]
  4-1     : [23, 15]
  4-2     : [24, 16]
  5-1     : [25, 25a]
  5-2     : [07, 08]
  # 5-2     : [26, 26a]
  # 7-2     : [07, 08]
  # 7-1     : [05, 06]
  6-2     : [03, 04]
  6-1     : [01, 02]

  8-1     : [37, 27]
  8-2     : [38, 28]
  9-1     : [39, 29]
  9-2     : [40, 30]
  10-1    : [41, 31]
  10-2    : [42, 32]
  11-1    : [43, 33]
  11-2    : [44, 34]
  12-1    : [45, 35]
  12-2    : [46, 36]
  14-2    : [53, 54]
  14-1    : [51, 52]
  13-2    : [49, 50]
  13-1    : [47, 48]

regions:
  One:
    - BlackBlack
    - Black
    - Blue
    - Brown
    - Gray
    - Green
    - BlueBlue
    - BrownBrown

    - Orange
    - Pink
    - Purple
    - Red
    - White
    - Yellow
    - WhiteWhite
    - YellowYellow
    - GrayGray
fourexperts:
  One:
    A: [27, 37, 28, 38, 29, 39, 30, 40, 47, 48, 49, 50, 51, 52, 53]
    B: [09, 17, 10, 18, 11, 19, 12, 20, 01, 02, 03, 04, 05, 06, 07]
    C: [36, 46, 35, 45, 34, 44, 33, 43, 32, 42, 56, 55, 54, 31, 41]
    D: [26a, 26, 25a, 25, 16, 24, 15, 23, 14, 22, 08, 13, 21, 46a, 56a]
4regions:
  FrontRight:
    - BlackBlack
    - Black
    - Blue
  BackRight:
    - Brown
    - Gray
    - Green
  FrontLeft:
    - Orange
    - Pink
    - Purple
  BackLeft:
    - Red
    - White
    - Yellow
    - YellowYellow
4expertseats:
  FrontRight:
    A: [01, 02, 03]
    B: [05, 06, 07]
    C: [17, 09, 18]
    D: [10, 19, 11]
  BackRight:
    A: [20, 12, 21]
    B: [13, 22, 14]
    C: [23, 15, 16]
    D: [24, 25, 26]
  FrontLeft:
    A: [47, 48, 49]
    B: [37, 27, 38]
    C: [39, 29, 40]
    D: [41, 31, 42]
  BackLeft:
    A: [43, 44, 33, 34]
    B: [45, 46, 35, 36]
    C: [47, 48, 49, 50 ]
    D: [ 51, 52, 53, 54 ]
