package Tennis::Model::dicDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

# use Catalyst;
# use Bett;

my $name = Tennis->config->{dic_database};
# my $name = "dic001";

__PACKAGE__->config(
    schema_class => 'Tennis::dicSchema',
    connect_info => {
        dsn => "dbi:Pg:dbname=$name",
        user => '',
        password => '',
    }
);

=head1 NAME

Tennis::Model::dicDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Tennis>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Tennis::dicSchema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

Dr Bean

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
