#!/usr/bin/perl

use strict;
use warnings;

use Text::Template;
use YAML qw/ LoadFile /;
my $leagueRound = $ARGV[0];
my $yaml = LoadFile("$leagueRound.yaml");

use IO::All;

my $io = io 'form.tmpl';
my $tmplString = $io->all;

my $n = 1;
my $tables = $yaml->{tables};
my $id = $yaml->{id};
PAGELOOP: while ( my $table = each %$tables )
{
	$tmplString .= "
\\begin{textblock}{8}(0,0)
\\textblocklabel{picture1}
\\mycard{\$\\heartsuit\$}
{$table}
{\\begin{Large}\\ding{220}<tmpl>$tables->{$table}->{A}</tmpl> <tmpl>$id->{$tables->{$table}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$tables->{$table}->{B}</tmpl> <tmpl>$id->{$tables->{$table}->{B}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,0)
\\textblocklabel{picture4}
\\mycard{\$\\spadesuit\$}
{$table}
{<tmpl>$tables->{$table}->{A}</tmpl> <tmpl>$id->{$tables->{$table}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$tables->{$table}->{B}</tmpl> <tmpl>$id->{$tables->{$table}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}
";
	$table = each %$tables;
	$tmplString .= "
\\begin{textblock}{8}(0,8)
\\textblocklabel{picture3}
\\mycard{\$\\diamondsuit\$}
{$table}
{\\begin{Large}\\ding{220}<tmpl>$tables->{$table}->{A}</tmpl> <tmpl>$id->{$tables->{$table}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$tables->{$table}->{B}</tmpl> <tmpl>$id->{$tables->{$table}->{B}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,8)
\\textblocklabel{picture2}
\\mycard{\$\\clubsuit\$}
{$table}
{<tmpl>$tables->{$table}->{A}</tmpl> <tmpl>$id->{$tables->{$table}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$tables->{$table}->{B}</tmpl> <tmpl>$id->{$tables->{$table}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}

\\begin{tiny}$n\\end{tiny}\\\\
\\newpage

";
	$n++;
	last PAGELOOP unless $table;
}

$tmplString .= '
\end{document}
';

my $league = substr( $leagueRound, 0, 1);
my $template = Text::Template->new(TYPE => 'STRING'
				, SOURCE => $tmplString
				, DELIMITERS => [ '<tmpl>', '</tmpl>' ] );

$yaml->{autogen} = "% This file, form.tex was autogenerated on " . localtime() . "by pair/form.pl";

open TEX, ">form.tex";
print TEX $template->fill_in( HASH => $yaml );

