package Dic::Command::fourhand;

# Last Edit: 2017 Mar 12, 03:42:43 PM
# $Id: /cloze/branches/ctest/dic.pl 1134 2007-03-17T11:05:37.500624Z greg  $

use strict;
use warnings;

use Dic -command;
sub usage_desc { "dic fourhand -c CTEST -t TOPIC -s STORY -f FORM" }

sub opt_spec  {
	return (
		["c=s", "cloze_style"]
		, ["t=s", "topic"]
		, ["s=s", "story"]
		, ["f=i", "form"]
	);
}

use IO::All;
use YAML qw/LoadFile/;
use Parse::RecDescent;
use Text::Template;
use Dic::Cloze::Fourhand qw/cloze/;
use List::Util qw/shuffle/;

our $RD_HINT = 1;

# my $round = LoadFile( "round.yaml" );
# my $league = LoadFile( "../league.yaml" );
# my @members = @{$league->{member}};
# my %ids = map { $_->{name} => $_->{id} } @members;
# my %names = map { $_->{id} => $_->{name} } @members;

sub execute {
	my ($self, $opt, $args) = @_;

	my ($cloze_style, $topic, $story, $form) = @$opt{qw/c t s f/};
	my ($text_list, $question) = LoadFile
		"/home/drbean/curriculum/topics/" . $topic . "/dic.yaml";

	my $fields = shift( @$text_list );


	my @latex = (
			{ page => 1, xy => "0,0" },
			{ page => 1, xy => "8,0" },
			{ page => 1, xy => "0,4" },
			{ page => 1, xy => "8,4" },
			{ page => 1, xy => "0,8" },
			{ page => 1, xy => "8,8" },
			{ page => 1, xy => "0,12" },
			{ page => 1, xy => "8,12" },
			# { page => 2, xy => "0,0" },
			# { page => 2, xy => "8,0" },
			# { page => 2, xy => "0,4" },
			# { page => 2, xy => "8,4" },
			# { page => 2, xy => "0,8" },
			# { page => 2, xy => "8,8" },
			# { page => 2, xy => "0,12" },
			# { page => 2, xy => "8,12" },
			# { page => 1, xy => "8,0" },
			# { page => 1, xy => "0,0" },
			# { page => 1, xy => "8,8" },
			# { page => 1, xy => "0,8" },
			# { page => 3, xy => "8,0" },
			# { page => 3, xy => "0,0" },
			# { page => 3, xy => "8,8" },
			# { page => 3, xy => "0,8" },
		);
	my $paging = 0;
	my $threepages = 0;

	my $tmpl = io "/home/drbean/class/ttb/dictation/tmpl/preamble.tmpl";
	my $tmplString = $tmpl->all;

	my $identifier;
	my %romanize = (
		0 => "Zero", 1 => "One", 2 => "Two", 3 =>"Three"
		, 4 => "Four", 5 => "Five", 6 => "Six", 7 =>"Seven"
		, 8 => "Eight", 9 => "Nine", 10 => "Ten", 11 =>"Eleven" 
	);

	$identifier = "$opt->{s}-$opt->{f}";
	my @text = grep { $_->[0] eq $identifier } @$text_list;
$DB::single=1;
	die "No texts or more than 1 text called $identifier\n" if @text != 1;

	my $lines = $text[0][4];
	my @lines = split /\n/, $lines;
	my $unclozeables = $text[0][5];
	my $text = cloze($cloze_style, $unclozeables, @lines);
	my $textA = $text->{A};
	my $textB = $text->{B};
	my $textC = $text->{C};
	my $textD = $text->{D};
	for my $j ( 0) {
		for my $i ( 0 .. 1) {
			$tmplString .= "
\\begin{textblock}{8}($latex[$j+4*$i]->{xy})
\\textblocklabel{picture$latex[$j+2*$i]->{xy}}
\\Large A\\\\
\\dicX$opt->{s}X$romanize{$opt->{f}}Xcard
{$textA}
\\end{textblock}\n";
			$tmplString .= "
\\begin{textblock}{8}($latex[$j+4*$i+1]->{xy})
\\textblocklabel{picture$latex[$j+2*$i+1]->{xy}}
\\Large B\\\\
\\dicX$opt->{s}X$romanize{$opt->{f}}Xcard
{$textB}
\\end{textblock}\n";
			$tmplString .= "
\\begin{textblock}{8}($latex[$j+4*$i+2]->{xy})
\\textblocklabel{picture$latex[$j+2*$i+2]->{xy}}
\\Large C\\\\
\\dicX$opt->{s}X$romanize{$opt->{f}}Xcard
{$textC}
\\end{textblock}\n";
			$tmplString .= "
\\begin{textblock}{8}($latex[$j+4*$i+3]->{xy})
\\textblocklabel{picture$latex[$j+2*$i+3]->{xy}}
\\Large D\\\\
\\dicX$opt->{s}X$romanize{$opt->{f}}Xcard
{$textD}
\\end{textblock}\n";
		}
		$tmplString .= "
\\begin{tiny}" . ( $j+1 ) . "\\end{tiny}\\newpage\n\n";


	}
	$tmplString .= '
\end{document}
';

	my $quiz;
	# $quiz->{cardIdentifier} = join ' ', map { m{^/.*/.*/(.*)$};$1 } @$textSources;
	$quiz->{cardIdentifier} = "$identifier";
	$quiz->{story} = $opt->{s};
	$quiz->{form} = $romanize{ $opt->{f} };
	$quiz->{autogen} = "% This file, dic_$opt->{s}_$opt->{f}.tex was autogenerated on " . localtime() . "by dic.pl out of cards.tmpl";

	my $template = Text::Template->new(TYPE => 'STRING', SOURCE => $tmplString
					, DELIMITERS => [ '<TMPL>', '</TMPL>' ] );
	open TEX, ">/home/drbean/curriculum/topics/$opt->{t}/dic_$opt->{s}_$opt->{f}.tex" or die "No open on " . $opt->{t} . ": " . $!;
	print TEX $template->fill_in( HASH => $quiz );

}

1;
