#!/usr/bin/perl

use strict;
use warnings;

use encoding qw/UTF8/;
use Text::Template;
use YAML qw/ LoadFile /;

my $round = LoadFile( "round.yaml" );
my $league = LoadFile( "../../league.yaml" );
my @members = @{$league->{member}};
my %ids = map { $_->{name} => $_->{id} } @members;
my %names = map { $_->{id} => $_->{name} } @members;

my $passquestions = $round->{pass};
my $passGrade = 9;
my $perfectGrade = 15;
my $totalQuestions = 9;
my $grade2questions = sub {
	my $grade = shift;
	return 1 + int ( $passquestions + ($grade-$passGrade)*($totalQuestions-$passquestions)/($perfectGrade-$passGrade));
};
my @grades = ( 9, 11, 13, 15 );
my @questions = map { $grade2questions->($_) } @grades;

use IO::All;

my $io = io 'form.tmpl';
my $tmplString = $io->all;

my $n = 1;
my $groups = $round->{group};
PAGELOOP: while ( my $group = each %$groups )
{
	$tmplString .= "
\\begin{textblock}{8}(0,0)
\\textblocklabel{picture1}
\\mycard{\$\\heartsuit\$}
{$group}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
{<tmpl>$groups->{$group}->{C}</tmpl> <tmpl>$ids{$groups->{$group}->{C}}</tmpl>}
{<tmpl>$groups->{$group}->{D}</tmpl> <tmpl>$ids{$groups->{$group}->{D}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,0)
\\textblocklabel{picture4}
\\mycard{\$\\spadesuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{C}</tmpl> <tmpl>$ids{$groups->{$group}->{C}}</tmpl>}
{<tmpl>$groups->{$group}->{D}</tmpl> <tmpl>$ids{$groups->{$group}->{D}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(0,8)
\\textblocklabel{picture3}
\\mycard{\$\\diamondsuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{C}</tmpl> <tmpl>$ids{$groups->{$group}->{C}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{D}</tmpl> <tmpl>$ids{$groups->{$group}->{D}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,8)
\\textblocklabel{picture2}
\\mycard{\$\\clubsuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
{<tmpl>$groups->{$group}->{C}</tmpl> <tmpl>$ids{$groups->{$group}->{C}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{D}</tmpl> <tmpl>$ids{$groups->{$group}->{D}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}

\\begin{tiny}$n\\end{tiny}\\\\
\\newpage

";
	$n++;
	last PAGELOOP unless defined $group;
}

$tmplString .= '
\end{document}
';

my $template = Text::Template->new(TYPE => 'STRING'
				, SOURCE => $tmplString
				, DELIMITERS => [ '<tmpl>', '</tmpl>' ] );

my $form;
$form->{autogen} = "% This file, form.tex was autogenerated on " . localtime() . "by form.pl";
$form->{league} = $league->{id};
# $form->{assistant} = $round->{assistant};
$form->{round} = $round->{round};
$form->{week} = $round->{week};
$form->{questions} = \@questions;
$form->{grades} = \@grades;

open TEX, ">form.tex";
print TEX $template->fill_in( HASH => $form );

