#!/usr/bin/perl

# Last Edit: 2013 Sep 29, 03:19:57 PM
# $Id: /dic/branches/comp/dic.pl 2601 2008-06-26T04:34:08.435934Z greg  $

use strict;
use warnings;

use Getopt::Long;
use Pod::Usage;

use FindBin '$Bin';
use lib ("$Bin", "$Bin/../lib");

my $man = 0;
my $help = 0;

GetOptions (
	'help|?' => \$help, man => \$man) or pod2usage(2);
pod2usage(1) if $help;
pod2usage(-exitstatus => 0, -verbose => 2) if $man;

use IO::All;
use YAML qw/LoadFile DumpFile/;
use Parse::RecDescent;
use Text::Template;
use Cloze qw/cloze/;
use List::Util qw/shuffle/;

our $RD_HINT = 1;

# my $round = LoadFile( "round.yaml" );
# my $league = LoadFile( "../league.yaml" );
# my @members = @{$league->{member}};
# my %ids = map { $_->{name} => $_->{id} } @members;
# my %names = map { $_->{id} => $_->{name} } @members;

# my $textSources = $round->{texts};

my $textSources = [ qw/greetings/ ];

my %texts;
my %nextQ;
my $qas;
for my $file ( @$textSources ) {
	my $i = 0;
	$qas = LoadFile $file;
	for my $q ( keys %$qas )
	#
	#my @dir = @$textSources;
	#for my $dir ( @$textSources )
	#{
	#	die "$dir not found or not a directory" unless -d $dir;
	#}
	#my $next;
	#my @blanks = (0)x2;
	#	my @files;
	#
	#sub sequences
	#{
	#	my $dir = shift;
	#	my @files = glob("$dir/*.txt");
	#	my @parallelforms = map { [ $_ ] } @files;
	#	while ( $dir = shift )
	{
		# my $qstring = $q . ": " . $qas->{$q};
		my $qstring = $q;
		my $as = $qas->{$q};
		# my $as = [ qw/True False/ ];
		$texts{$file}{$q} = cloze($qstring,$as);
	}
	$nextQ{$file} = iterator($texts{$file});
}

my $tmpl = io "$Bin/dic.tmpl";
my $tmplString = $tmpl->all;

# my $groups = $round->{group};
my $groups = { Black => undef, Blue => undef, Brown => undef };

my @latex = (
		{ page => 1, xy => "8,0" },
		{ page => 1, xy => "0,0" },
		{ page => 1, xy => "8,8" },
		{ page => 1, xy => "0,8" },
		{ page => 2, xy => "8,0" },
		{ page => 2, xy => "0,0" },
		{ page => 2, xy => "8,8" },
		{ page => 2, xy => "0,8" },
		{ page => 3, xy => "8,0" },
		{ page => 3, xy => "0,0" },
		{ page => 3, xy => "8,8" },
		{ page => 3, xy => "0,8" },
	);
my $paging = 0;
my $threepages = 0;

foreach my $group ( keys %$groups )
{
	# my %group =  %{$groups->{$group}}; 
	my @texts = map { my $i=0; $nextQ{$textSources->[$i]}->() } 0..7;
	# my @group =  %{$groups->{$group}}; 
	# my $text = $next->();
	$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\myAcard
{$texts[0][0]}
{$texts[2][0]}
{$texts[4][0]}
{$texts[6][0]}
{$texts[9][0]}
{$texts[11][0]}
{$texts[13][0]}
{$texts[15][0]}
\\end{textblock}\n";

		&paging;

		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\myBcard
{$texts[1][0]}
{$texts[3][0]}
{$texts[5][0]}
{$texts[7][0]}
{$texts[8][0]}
{$texts[10][0]}
{$texts[12][0]}
{$texts[14][0]}
\\end{textblock}\n";

		&paging;

}

$tmplString .= '
\end{document}
';

my $quiz;
$quiz->{cardIdentifier} = join ' ', map { s{.*/(\w+)$}{$1} } @$textSources;
# $quiz->{cardIdentifier} = join ' ', map { m{^/.*?/.*?/(.*)$};$1 } @$textSources;
# ($quiz->{cardIdentifier} = $textSources ) =~ 
				# s{.*/(\w+/\w+)/?$}{$1};
				# s{.*/(\w+/(?:dic|cloze|book)\d?)\.txt$}{$1};
				# s|.*/(\S+/\S+).txt$|$1|;
$quiz->{autogen} = "% This file, cards.tex was autogenerated on " . localtime() . "by dic.pl out of dic.tmpl";

my $template = Text::Template->new(TYPE => 'STRING', SOURCE => $tmplString
				, DELIMITERS => [ '<TMPL>', '</TMPL>' ] );
open TEX, ">cards.tex";
print TEX $template->fill_in( HASH => $quiz );

sub iterator
{
	my $qas = shift;
	my $number = keys %$qas;
	my @keys = keys %$qas;
	my $index = 0;
	my ($nextText, $nextFile);
	return sub
	{
		my $next = $keys[$index];
		if (++$index == $number)
		{
			$index = 0 ;
			my @newqns = @keys[ shuffle(0..$number-1) ];
			@keys = @newqns;
		}
		my $textA = $qas->{$next}->{A};
		my $textB = $qas->{$next}->{B}; # join '', @{$nextText->{B}};
		return ( $textA, $textB );
	};
}

sub paging
{       if ($paging == 3 or $paging == 7 or $paging == 11 )
        {
                $tmplString .= "
\\begin{tiny}" . ($threepages + $latex[$paging]->{page}) .                      +"\\end{tiny}\\newpage\n\n";
        }
        if ($paging == 11) { $threepages = $threepages+3; $paging = 0; }
        else { $paging++; }
}
