#!/usr/bin/perl

use strict;
use warnings;

use Text::Template;
use YAML qw/ LoadFile /;

use File::Spec;
use File::Basename;
my $roundN = basename( File::Spec->rel2abs('.') );
my $round = LoadFile( "round.yaml" );
my $league = LoadFile( "../league.yaml" );
my @members = @{$league->{member}};
my %ids = map { $_->{name} => $_->{id} } @members;
my %names = map { $_->{id} => $_->{name} } @members;
my $assistants;
if ( -e '../assistants.yaml' )
{
	my $assistantFile = LoadFile '../assistants.yaml';
	$assistants = $assistantFile->{$roundN};
}
elsif ( $round->{assistant} and $round->{assistant} !~ m/No.*ne/ ) {
	$assistants = $round->{assistant};
}

use IO::All;

my $io = io 'form.tmpl';
my $tmplString = $io->all;
my $questioner_rules = "\\normalsize 1. You ask your partner the questions. Your partner answers the questions. \\vspace{-0.2cm} \\par 2. If your partner is correct more than half the time, she/he wins 1 point and you win 0.5 points. If she/he is correct LESS than half the time, YOU win 1 point and he/she wins 0.5 points. \\vspace{-0.2cm} \\par 3. Read your partner the questions and let him/her write them down. \\vspace{-0.2cm} \\par 4. Read the questions as many times as your partner wants. \\vspace{-0.2cm} \\par 5. Let your partner write down his/her answers. \\vspace{-0.2cm} \\par 6. Copy your partner's answers on your answer sheet. \\vspace{0.6cm}";
my $answerer_rule = "\\normalsize 1. Your partner will read you some questions. Your job is to answer the questions. \\vspace{-0.2cm} \\par 2. If you get more than half the answers correct, you win 1 point and your partner wins 0.5 points. If you get less than half the questions correct, you only win 0.5 points and he/she wins the 1 point. \\vspace{-0.2cm} \\par 3. Listen to your partner and write the questions down. \\vspace{-0.2cm} \\par 4. Ask him/her to read the questions as many times as you want. \\vspace{-0.2cm} \\par 5. Write down your answers on your card. \\vspace{-0.2cm} \\par 6. Copy your answers to your partner's card. \\vspace{0.6cm}";
my $n = 1;
my $groups = $round->{group};
my $bye;
PAGELOOP: while ( my $group = each %$groups )
{
	if ( exists $groups->{$group}->{Bye} )
	{
		$bye = $groups->{$group}->{Bye};
		next PAGELOOP;
	}
	$tmplString .= "
\\begin{textblock}{8}(0,0)
\\textblocklabel{picture1}
\\mycard{\$\\heartsuit\$}
{$group}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,0)
\\textblocklabel{picture4}
\\mycard{\$\\spadesuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}
";
	$group = each %$groups;
	$tmplString .= "
\\begin{textblock}{8}(0,8)
\\textblocklabel{picture3}
\\mycard{\$\\diamondsuit\$}
{$group}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
{<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>}
\\end{textblock}

\\begin{textblock}{8}(8,8)
\\textblocklabel{picture2}
\\mycard{\$\\clubsuit\$}
{$group}
{<tmpl>$groups->{$group}->{A}</tmpl> <tmpl>$ids{$groups->{$group}->{A}}</tmpl>}
{\\begin{Large}\\ding{220}<tmpl>$groups->{$group}->{B}</tmpl> <tmpl>$ids{$groups->{$group}->{B}}</tmpl>\\end{Large} \\begin{tiny}Signature:\\hrulefill\\end{tiny}}
\\end{textblock}

\\begin{tiny}$n\\end{tiny}\\\\
\\newpage

";
	$n++;
	last PAGELOOP unless defined $group;
}

$tmplString .= '
\end{document}
';

my $template = Text::Template->new(TYPE => 'STRING'
				, SOURCE => $tmplString
				, DELIMITERS => [ '<tmpl>', '</tmpl>' ] );

my $form;
$form->{autogen} = "% This file, form.tex was autogenerated on " . localtime() . "by form.pl";
$form->{league} = $league->{league};
$form->{assistant} = [keys %$assistants] if $assistants;
@{$form->{assistantId}} = map { $ids{$_} } keys %$assistants if $assistants;
$form->{bye} = $bye;
$form->{byeId} = $ids{$bye} if $bye;
$form->{round} = $round->{round};
$form->{week} = $round->{week};

open TEX, ">form.tex";
print TEX $template->fill_in( HASH => $form );

