---
id: MUST, Room 207
pairs:
  1 : [02, 01]
  2 : [04, 03]
  3 : [06, 05]
  4 : [08, 07]
  5 : [10, 09]
  6 : [12, 11]
  7 : [14, 13]
  8 : [16, 15]
  9 : [18, 17]
  10: [20, 19]
  11: [22, 21]
  12: [24, 23]
  13: [26, 25]
  14: [28, 27]
  15: [30, 29]
  16: [32, 31]
  17: [34, 33]
  18: [36, 35]
  19: [38, 37]
  20: [40, 39]
  21: [42, 41]
  22: [44, 43]
  23: [46, 45]
  24: [48, 47]
  25: [50, 49]
pairexperts:
  1 : [11, 01]
  2 : [04, 10]
  3 : [15, 05]
  4 : [08, 14]
  5 : [03, 09]
  6 : [12, 02]
  7 : [07, 13]
  8 : [16, 06]
  9 : [27, 17]
  10: [20, 26]
  11: [31, 21]
  12: [24, 30]
  13: [19, 25]
  14: [28, 18]
  15: [23, 29]
  16: [32, 22]
  17: [43, 33]
  18: [36, 42]
  19: [47, 37]
  20: [40, 46]
  21: [35, 41]
  22: [44, 34]
  23: [39, 45]
  24: [48, 38]
  25: [56, 49]
colors:
  1 : #ff0000
  2 : #ff5050
  3 : #ff6600
  4 : #ff9933

  5 : #ffcc00
  6 : #ffff66
  7 : #ccff66
  8 : #99ff66

  9 : #66ff33
  10: #66ff99
  11: #66ffcc
  12: #00ffcc

  13: #00ffff
  14: #33cccc
  15: #00ccff
  16: #0099ff

  17: #66a3e0
  18: #6685e0
  19: #6666ff
  20: #9999eb

  21: #9999cc
  22: #666669
  23: #757575
  24: #909090

  25: #c5c5c5
  26: #f0f0f0
  Black     : #333333
  BlackBlack: #555555
  Blue      :
  BlueBlue  : #3399ff
  Brown     :
  BrownBrown: #993333
  DarkBlue  :
  DarkGreen :
  Gray      :
  GrayGray  : #f0f0f0
  Green     :
  GreenGreen: #00ff00
  LightBlue :
  LightGreen:
  Orange    :
  Pink      :
  Purple    :
  Red       :
  White     :
  Yellow    :
  1/1     : Black
  1/2     : Black
  2/1     : Blue
  2/2     : Blue
  3/1     : Brown
  3/2     : Brown
  4/1     : Gray
  4/2     : Gray
  5/1     : Green
  5/2     : Green
  6/1     : Black
  6/2     : Black
  # 7/2     : [65, 65]
  # 7/1     : [63, 62]

  8/1     : Orange
  8/2     : Orange
  9/1     : Pink
  9/2     : Pink
  10/1    : Purple
  10/2    : Purple
  11/1    : Red
  11/2    : Red
  12/1    : White
  12/2    : White
  13/2    : Yellow
  13/1    : Yellow
  14/1    : Orange
  14/2    : Orange
regions:
  Front:
    - Black
    - Gray
    - Orange
    - Red
  Middle:
    - Brown
    - LightBlue
    - Pink
    - White
  Back:
    - DarkGreen
    - LightGreen
    - Purple
    - Yellow
    - BlackBlack
fourexperts:
  Front:
    A : [08, 07, 16, 15]
    B : [06, 05, 14, 13]
    C : [04, 03, 12, 11]
    D : [02, 01, 10, 09]
  Middle:
    A: [24, 23, 32, 31]
    B: [22, 21, 30, 29]
    C: [20, 19, 28, 27]
    D: [18, 17, 26, 25]
  Back:
    A  : [40, 39, 48, 47]
    B  : [38, 37, 46, 45]
    C  : [36, 35, 44, 43]
    D  : [34, 33, 42, 41]
fours:
  White       : [08, 07, 16, 15]
  Pink        : [06, 05, 14, 13]
  Gray        : [04, 03, 12, 11]
  Black       : [02, 01, 10, 09]

  Yellow      : [24, 23, 32, 31]
  Purple      : [22, 21, 30, 29]
  Green       : [20, 19, 28, 27]
  Blue        : [18, 17, 26, 25]

  YellowYellow: [40, 39, 48, 47]
  Red         : [38, 37, 46, 45]
  Orange      : [36, 35, 44, 43]
  Brown       : [34, 33, 42, 41]

  BlueBlue    : [52, 51, 62, 61]
  BlackBlack  : [50, 49, 60, 64]
threes:

  Black       : [05, 04, 03]
  Blue        : [02, 12, 13]
  Brown       : [14, 15, 25]
  Gray        : [24, 23, 22]

  Green       : [35, 34, 33]
  BlackBlack  : [32, 42, 43]
  BlueBlue    : [44, 45, 55]
  BrownBrown  : [54, 53, 52]

  Orange      : [09, 08, 07]
  Pink        : [06, 16, 17]
  Purple      : [18, 19, 29]
  Red         : [28, 27, 26]

  PinkPink    : [39, 38, 37]
  White       : [36, 37, 38]
  Yellow      : [39, 49, 48]
  OrangeOrange: [47, 46, 56]

  PurplePurple: [68,67,65]

twos:
  1/1     : [05, 04]
  1/2     : [03, 02]
  2/1     : [15, 14]
  2/2     : [13, 12]
  3/1     : [25, 24]
  3/2     : [23, 22]
  4/1     : [35, 34]
  4/2     : [33, 32]
  5/1     : [45, 44]
  5/2     : [43, 42]
  6/1     : [55, 54]
  6/2     : [53, 52]
  # 7/2     : [65, 65]
  # 7/1     : [63, 62]

  8/1     : [09, 08]
  8/2     : [07, 06]
  9/1     : [19, 18]
  9/2     : [17, 16]
  10/1    : [29, 28]
  10/2    : [27, 26]
  11/1    : [39, 38]
  11/2    : [37, 36]
  12/1    : [49, 48]
  12/2    : [47, 46]
  13/2    : [59, 58]
  13/1    : [57, 56]
  14/1    : [69, 68]
  14/2    : [67, 66]
