---
id: A902
pairs:
  1 : [02, 01]
  2 : [04, 03]
  3 : [06, 05]
  4 : [08, 07]
  5 : [10, 09]
  6 : [12, 11]
  7 : [14, 13]
  8 : [16, 15]
  9 : [18, 17]
  10: [20, 19]
  11: [22, 21]
  12: [24, 23]
  13: [26, 25]
  14: [28, 27]
  15: [30, 29]
  16: [32, 31]
  17: [34, 33]
  18: [36, 35]
  19: [38, 37]
  20: [40, 39]
  21: [42, 41]
  22: [44, 43]
  23: [46, 45]
  24: [48, 47]
  25: [50, 49]
pairexperts:
  1 : [11, 01]
  2 : [04, 10]
  3 : [15, 05]
  4 : [08, 14]
  5 : [03, 09]
  6 : [12, 02]
  7 : [07, 13]
  8 : [16, 06]
  9 : [27, 17]
  10: [20, 26]
  11: [31, 21]
  12: [24, 30]
  13: [19, 25]
  14: [28, 18]
  15: [23, 29]
  16: [32, 22]
  17: [43, 33]
  18: [36, 42]
  19: [47, 37]
  20: [40, 46]
  21: [35, 41]
  22: [44, 34]
  23: [39, 45]
  24: [48, 38]
  25: [56, 49]
colors:
  1 : #ff0000
  2 : #ff5050
  3 : #ff6600
  4 : #ff9933

  5 : #ffcc00
  6 : #ffff66
  7 : #ccff66
  8 : #99ff66

  9 : #66ff33
  10: #66ff99
  11: #66ffcc
  12: #00ffcc

  13: #00ffff
  14: #33cccc
  15: #00ccff
  16: #0099ff

  17: #66a3e0
  18: #6685e0
  19: #6666ff
  20: #9999eb

  21: #9999cc
  22: #666669
  23: #757575
  24: #909090

  25: #c5c5c5
  26: #f0f0f0
  Black     : #c5c5c5
  BlackBlack: #909090
  Blue      :
  BlueBlue  : Blue
  Brown     :
  BrownBrown: Brown
  DarkBlue  :
  DarkGreen :
  Gray      :
  GrayGray  : #c5c5c5
  Green     :
  GreenGreen: Green
  LightBlue :
  LightGreen:
  Orange    :
  OrangeOrange: Orange
  Pink      :
  PinkPink  : Pink
  Purple    :
  PurplePurple: Purple
  Red       :
  White     :
  Yellow    :
  YellowYellow: Yellow
regions:
  Front:
    - Black
    - Gray
    - Pink
    - White
  Middle:
    - Blue
    - Green
    - Purple
    - Yellow
  Back:
    - Brown
    - Orange
    - Red
    - YellowYellow
    - BlackBlack
fourexperts:
  Front:
    A : [08, 07, 16, 15]
    B : [06, 05, 14, 13]
    C : [04, 03, 12, 11]
    D : [02, 01, 10, 09]
  Middle:
    A: [24, 23, 32, 31]
    B: [22, 21, 30, 29]
    C: [20, 19, 28, 27]
    D: [18, 17, 26, 25]
  Back:
    A  : [40, 39, 48, 47, 55]
    B  : [38, 37, 46, 45, 53]
    C  : [36, 35, 44, 43, 51]
    D  : [34, 33, 42, 41, 49]
fours:
  White       : [08, 07, 16, 15]
  Pink        : [06, 05, 14, 13]
  Gray        : [04, 03, 12, 11]
  Black       : [02, 01, 10, 09]


  Purple      : [22, 21, 30, 29]
  Green       : [20, 19, 28, 27]
  Blue        : [18, 17, 26, 25]


  Red         : [38, 37, 46, 45]
  Orange      : [36, 35, 44, 43]
  Brown       : [34, 33, 42, 41]

  WhiteWhite  : [56, 55, 64, 63]
  PinkPink    : [54, 53, 62, 61]
  GrayGray    : [52, 51, 60, 59]
  BlackBlack  : [50, 49, 58, 57]

  YellowYellow: [72, 71, 80, 79]
  PurplePurple: [70, 69, 78, 77]
  GreenGreen  : [68, 67, 76, 75]
  BlueBlue    : [66, 65, 74, 73]

  BrownBrown  : [83, 82, 81]
  OrangeOrange: [86, 85, 84]
