#!/usr/bin/perl

# Last Edit: 2007 May 09, 01:59:16 PM
# $Id: /words/card.pl 1969 2008-04-18T09:37:35.763722Z greg  $

use strict;
use warnings;

use IO::All;
use YAML qw/LoadFile DumpFile/;
use Text::Template;
use Cloze qw/cloze/;
use List::Util qw/shuffle/;
our $RD_HINT = 1;

my $round = LoadFile( "round.yaml" );
my $league = LoadFile( "../league.yaml" );
my @members = @{$league->{member}};
my %ids = map { $_->{name} => $_->{id} } @members;
my %names = map { $_->{id} => $_->{name} } @members;

my $textSources = $round->{texts};

my @dir = @$textSources;
for my $dir ( @$textSources )
{
	die "$dir not found or not a directory" unless -d $dir;
}
my $next;
my @blanks = (0)x2;
	my @files;

sub sequences
{
	my $dir = shift;
	my @files = glob("$dir/*.txt");
	my @parallelforms = map { [ $_ ] } @files;
	while ( $dir = shift )
	{
		my @extendedforms;
		my @alternatives =  glob("$dir/*.txt");
		for my  $file ( @alternatives )
		{
			for my $form ( @parallelforms )
			{
				push @extendedforms, [@$form, $file];
			}
		}
		@parallelforms = @extendedforms;
	}
	return @parallelforms;
}

my @parallelfiles = sequences(@dir);
my @texts;
for my $files ( @parallelfiles )
{
	my @files = map { io $_ } @$files;
	my @lines;
	push @{$lines[$_]}, ( $files[$_]->getlines ) for 0..$#files;
	my @blanks = (0)x2;
	my @text;
	(@blanks[0,1], $text[$_]) = cloze(@blanks, @{$lines[$_]})
								for 0..$#files;
	push @texts, \@text;
}
$next = nextText(@texts);

my $tmpl = io 'dic.tmpl';
my $tmplString = $tmpl->all;

my $groups = $round->{group};

my @latex = (
		{ page => 1, xy => "8,0" },
		{ page => 1, xy => "0,0" },
		{ page => 1, xy => "8,8" },
		{ page => 1, xy => "0,8" },
		{ page => 2, xy => "8,0" },
		{ page => 2, xy => "0,0" },
		{ page => 2, xy => "8,8" },
		{ page => 2, xy => "0,8" },
		{ page => 3, xy => "8,0" },
		{ page => 3, xy => "0,0" },
		{ page => 3, xy => "8,8" },
		{ page => 3, xy => "0,8" },
	);
my $paging = 0;
my $threepages = 0;

foreach my $group ( keys %$groups )
{
	my @group =  %{$groups->{$group}}; 
	my $text = $next->();
	$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard" . (join "\n", map { "{$text->[$_]->{A}}" } 0..$#$textSources) . "
\\end{textblock}\n";

		&paging;

		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
\\mycard" . (join "\n", map { "{$text->[$_]->{B}}" } 0..$#$textSources) . "
\\end{textblock}\n";

		&paging;

}

$tmplString .= '
\end{document}
';

my $quiz;
# $quiz->{cardIdentifier} = join ' ', map { s{.*/(\w+)$}{$1} } @$textSources;
$quiz->{cardIdentifier} = join ' ', map { m{^/.*?/.*?/(.*)$};$1 } @$textSources;
# ($quiz->{cardIdentifier} = $textSources ) =~ 
				# s{.*/(\w+/\w+)/?$}{$1};
				# s{.*/(\w+/(?:dic|cloze|book)\d?)\.txt$}{$1};
				# s|.*/(\S+/\S+).txt$|$1|;
$quiz->{autogen} = "% This file, pair/cards.tex was autogenerated on " . localtime() . "by dic.pl out of dic.tmpl";
$quiz->{sections} = @$textSources;
$quiz->{sectionsLatex} = join "\n", map {
	"  \\item \\parbox{7.0cm}{\\normalsize #$_}\n\\vspace{0.2cm}"
	} 1..@$textSources;

my $template = Text::Template->new(TYPE => 'STRING', SOURCE => $tmplString
				, DELIMITERS => [ '<TMPL>', '</TMPL>' ] );
open TEX, ">cards.tex";
print TEX $template->fill_in( HASH => $quiz );

sub nextText
{
	my @texts = @_;
	my $number = @texts;
	my $index = 0;
	my $nextText;
	return sub
	{
		$nextText = $texts[$index];
		if (++$index == $number)
		{
			$index = 0 ;
			@texts[0..$number-1] = @texts[shuffle(0..$number-1)];
		}
		# $index = int rand( $number );
		return $nextText;
	};
}

sub paging
{       if ($paging == 3 or $paging == 7 or $paging == 11 )
        {
                $tmplString .= "
\\begin{tiny}" . ($threepages + $latex[$paging]->{page}) .                      +"\\end{tiny}\\newpage\n\n";
        }
        if ($paging == 11) { $threepages = $threepages+3; $paging = 0; }
        else { $paging++; }
}
