#!/usr/bin/perl

# Last Edit: 2007 Jun 20, 10:34:22 PM
# $Id$

use strict;
use warnings;

use IO::All;
use YAML qw/LoadFile DumpFile/;
use Text::Template;
use Cloze qw/cloze/;
use List::Util qw/shuffle max/;

our $RD_HINT = 1;

my $round = LoadFile( "round.yaml" );
my $league = LoadFile( "../league.yaml" );
my @members = @{$league->{member}};
my %ids = map { $_->{name} => $_->{id} } @members;
my %names = map { $_->{id} => $_->{name} } @members;

my $textSources = $round->{texts};
my $questionN = $round->{questions};
my $qNumber = max @$questionN;

my %questions;
my %nextQ;
my $qas;
for my $file ( @$textSources ) {
	die "$file a directory" if -d $file;
	my $i = 0;
	$qas = LoadFile $file;
	for my $q ( keys %$qas )
	{
		my $as = $qas->{$q};
		$questions{$file}{$q} = $as;
	}
	$nextQ{$file} = iterator($questions{$file});
}

my $tmpl = io 'dic.tmpl';
my $tmplString = $tmpl->all;

my $groups = $round->{group};

my @latex = (
		{ page => 1, xy => "8,0" },
		{ page => 1, xy => "0,0" },
		{ page => 1, xy => "8,8" },
		{ page => 1, xy => "0,8" },
		{ page => 2, xy => "8,0" },
		{ page => 2, xy => "0,0" },
		{ page => 2, xy => "8,8" },
		{ page => 2, xy => "0,8" },
		{ page => 3, xy => "8,0" },
		{ page => 3, xy => "0,0" },
		{ page => 3, xy => "8,8" },
		{ page => 3, xy => "0,8" },
	);
my $paging = 0;
my $threepages = 0;

foreach my $group ( keys %$groups )
{
	my %group =  %{$groups->{$group}}; 
	for my $player ( values %group )
	{
		$tmplString .= "
\\begin{textblock}{8}($latex[$paging]->{xy})
\\textblocklabel{picture$latex[$paging]->{xy}}
";
		my $n = 0;
		for my $file ( @$textSources )
		{
			my $Qnumber = $questionN->[$n++];
			my @texts = map { $nextQ{$file}->() } 0..$Qnumber-1;
			$tmplString .= "\\myblock\n" .
			(join "\n", map {
"{\\myquestion{".($_+1).". $texts[$_][0]}
{$texts[$_][1][0]}
{$texts[$_][1][1]}}" } 0..$qNumber-1 ) . "\n";
			$tmplString .= "\\par\n";
		}
		$tmplString .= "\\end{textblock}\n";

			&paging;
	}
}

$tmplString .= '
\end{document}
';

my $quiz;
# $quiz->{cardIdentifier} = join ' ', map { s{.*/(\w+)$}{$1} } @$textSources;
$quiz->{cardIdentifier} = join ' ', map { m{^/.*/.*/(.+)$};$1 } @$textSources;
# ($quiz->{cardIdentifier} = $textSources ) =~ 
				# s{.*/(\w+/\w+)/?$}{$1};
				# s{.*/(\w+/(?:dic|cloze|book)\d?)\.txt$}{$1};
				# s|.*/(\S+/\S+).txt$|$1|;
$quiz->{autogen} = "% This file, cards.tex was autogenerated on " . localtime() . "by dic.pl out of dic.tmpl";
$quiz->{questionN} = $qNumber;
$quiz->{questions} = join "\n", map { "\\item #$_\n\\vspace{-0.1cm}"
	} 1..$qNumber;

my $template = Text::Template->new(TYPE => 'STRING', SOURCE => $tmplString
				, DELIMITERS => [ '<TMPL>', '</TMPL>' ] );
open TEX, ">cards.tex";
print TEX $template->fill_in( HASH => $quiz );

sub iterator
{
	my $qas = shift;
	my $number = keys %$qas;
	my @keys = keys %$qas;
	my $index = 0;
	my $question;
	return sub
	{
		my $next = $keys[$index];
		if (++$index == $number)
		{
			$index = 0 ;
			my @newqns = @keys[ shuffle(0..$number-1) ];
			@keys = @newqns;
		}
		my $question = $next;
		my $distractors = $qas->{$next};
		return [$question, $distractors];
	};
}

sub paging
{       if ($paging == 3 or $paging == 7 or $paging == 11 )
        {
                $tmplString .= "
\\begin{tiny}" . ($threepages + $latex[$paging]->{page}) .                      +"\\end{tiny}\\newpage\n\n";
        }
        if ($paging == 11) { $threepages = $threepages+3; $paging = 0; }
        else { $paging++; }
}
